name: BGB
run-name: ${{inputs.symbol || '' }}

on:
  push:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  pull_request: # Runs on pull request creation and updates
  workflow_dispatch:
    inputs:
      symbol:
        required: true
        default: 'BGB/USDT'

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.11', '3.12', '3.13']
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python bgb.py
        env:
          symbol: ${{ inputs.symbol }}
