name: Pyth Price feeds

on:
  push:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  pull_request: # Runs on pull request creation and updates

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.11', '3.12', '3.13']
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python pyth_price_feed.py

